config/routes.rb
Rails.application.routes.draw do
  get 'profiles/edit'

  get 'profiles/update'

  resources :users
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  resource :profile, only: [:edit, :update]
  resources :skills, only: :show
  resources :interests, only: :show
  resources :locations, only: :show
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- most_used_skills.each do |skill|
  %li
    = link_to skill.name.capitalize, skill_path(skill)

- if user_signed_in?
  %li
    = link_to 'My Profile', edit_profile_path
  %li
    = link_to 'Sign out', signout_path
- else
  %li
    = link_to signin_path do
      Login or Signup

app/views/layouts/_notices.html.haml
.col-md-offset-1.col-md-10
  - flash.each do |type, message|
    %div{:class => "alert #{bootstrap_class_for(type)} fade in mt10"}
      %button.close{"data-dismiss" => "alert"} ×
      = message
.clearfix

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Developersin'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Developersin'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/layouts/flatty.html.haml
!!! 5
%html(lang="en")
  %head
    = analytics_init if Rails.env.production?
    = javascript_include_tag "application", "flatty", 'data-turbolinks-track' => true
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? "#{yield(:title)} - #BEDevTeam" : "#BEDevTeam"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag "flatty", :media => "all"
    = yield(:page_stylesheet) if content_for?(:page_stylesheet)


  %body{id: "#{controller_name}-#{action_name}"}
    %header
      %a{:href => "https://github.com/cedricbousmanne/BEDevTeam"}
        %img{:alt => "Fork me on GitHub", "data-canonical-src" => "https://s3.amazonaws.com/github/ribbons/forkme_right_white_ffffff.png", :src => "https://camo.githubusercontent.com/52760788cde945287fbb584134c4cbc2bc36f904/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f77686974655f6666666666662e706e67", :style => "position: absolute; top: 0; right: 0; border: 0;"}/
      .content
        .col-md-5
          %h1
            = link_to root_path do
              Belgian Developers Team
        .col-md-7
          = render "layouts/navigation"
    #belgian-flag
      #black.flag-third.pull-left
      #yellow.flag-third.pull-left
      #red.flag-third.pull-left
      .clearfix
    .content
      = render "layouts/notices"
      = yield
      .clearfix
    %footer.mt40
      .row
        .col-md-4
          = render partial: "layouts/footer/list", locals: { list: most_used_skills, type: "skill" }
        .col-md-4
          = render partial: "layouts/footer/list", locals: { list: most_used_interests, type: "interest" }
        .col-md-4
          = render partial: "layouts/footer/list", locals: { list: most_used_locations, type: "location" }
      .row.ac
        photo credit:
        %a{:href => "http://pixabay.com/fr/site-web-code-html-codage-647013/"} lmonk72 CC0 Public Domain
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = yield(:page_javascript) if content_for?(:page_javascript)